version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@vercel/node"
        update-types: ["version-update:semver-major"]
