// GENERATED by scripts/generate-email-buttons.py. Do not edit.
//
// Filenames carry a content hash because Vercel serves /public as
// immutable for a year, so a changed button must be a new URL.

export const EMAIL_BUTTON_FILES: Record<string, string> = {
  'btn-affiliate': 'btn-affiliate.427c1a46.png',
  'btn-services': 'btn-services.0f8e8e86.png',
  'btn-chip-in': 'btn-chip-in.e97fdcf6.png',
  'btn-pay-deposit': 'btn-pay-deposit.cb17233e.png',
  'btn-pay-balance': 'btn-pay-balance.f1aa2ace.png',
  'btn-open-gallery': 'btn-open-gallery.91b13346.png',
  'btn-view-invoice': 'btn-view-invoice.d9be4898.png',
};
