#!/bin/bash
# Supabase Environment Variables Setup Script
# Generated by scripts/generate-env-script.js
# Usage: ./scripts/setup-supabase-env.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_DIR"

echo "🔐 Supabase Environment Setup"
echo ""
echo "📋 Supabase database and authentication"
echo ""


# Supabase project URL
echo "📝 VITE_SUPABASE_URL"
echo "   Get from: https://supabase.com/dashboard/project/nonaqhllakrckbtbawrb/settings/api-keys"
echo "   Default: https://nonaqhllakrckbtbawrb.supabase.co"
read -p "Enter VITE_SUPABASE_URL (or press Enter for default): " VITE_SUPABASE_URL_INPUT

VITE_SUPABASE_URL_VALUE="${VITE_SUPABASE_URL_INPUT:-https://nonaqhllakrckbtbawrb.supabase.co}"

if [ -z "$VITE_SUPABASE_URL_VALUE" ]; then
  echo "❌ Error: VITE_SUPABASE_URL cannot be empty"
  exit 1
fi

# Supabase publishable/anonymous key
echo "📝 VITE_SUPABASE_ANON_KEY"
echo "   Get from: https://supabase.com/dashboard/project/nonaqhllakrckbtbawrb/settings/api-keys"

read -p "Enter VITE_SUPABASE_ANON_KEY: " VITE_SUPABASE_ANON_KEY_INPUT

VITE_SUPABASE_ANON_KEY_VALUE="${VITE_SUPABASE_ANON_KEY_INPUT}"

if [ -z "$VITE_SUPABASE_ANON_KEY_VALUE" ]; then
  echo "❌ Error: VITE_SUPABASE_ANON_KEY cannot be empty"
  exit 1
fi






# Build env file content
ENV_CONTENT="# Supabase Configuration
# Generated by setup-supabase-env.sh
"

ENV_CONTENT+="VITE_SUPABASE_URL=$VITE_SUPABASE_URL_VALUE\n"
ENV_CONTENT+="VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY_VALUE\n"




# Append to .env.local (or create if doesn't exist)
if [ -f .env.local ]; then
  # Remove existing entries for these variables
  
  grep -v "^VITE_SUPABASE_URL=" .env.local > .env.local.tmp || true
  mv .env.local.tmp .env.local
  
  grep -v "^VITE_SUPABASE_ANON_KEY=" .env.local > .env.local.tmp || true
  mv .env.local.tmp .env.local
  
fi

echo -e "$ENV_CONTENT" >> .env.local

echo ""
echo "✅ Supabase environment variables added to .env.local!"

# Ask about Vercel
echo ""
read -p "Do you want to set Vercel environment variables? (y/n): " SET_VERCEL

if [ "$SET_VERCEL" = "y" ] || [ "$SET_VERCEL" = "Y" ]; then
  echo ""
  echo "🔐 Checking Vercel CLI..."
  
  # Use npx vercel if vercel command not found
  if command -v vercel &> /dev/null; then
    VERCEL_CMD="vercel"
  else
    VERCEL_CMD="npx vercel"
    echo "⚠️  Using npx vercel (Vercel CLI not installed globally)"
  fi
  
  echo "📝 Setting Vercel environment variables..."
  

  # Set VITE_SUPABASE_URL
  echo "$VITE_SUPABASE_URL_VALUE" | $VERCEL_CMD env add VITE_SUPABASE_URL production preview development 2>/dev/null || \
    echo "⚠️  VITE_SUPABASE_URL might already be set. Use '$VERCEL_CMD env ls' to check."

  # Set VITE_SUPABASE_ANON_KEY
  echo "$VITE_SUPABASE_ANON_KEY_VALUE" | $VERCEL_CMD env add VITE_SUPABASE_ANON_KEY production preview development 2>/dev/null || \
    echo "⚠️  VITE_SUPABASE_ANON_KEY might already be set. Use '$VERCEL_CMD env ls' to check."




  echo ""
  echo "✅ Vercel environment variables set!"
  echo "   Run '$VERCEL_CMD --prod' to redeploy with new variables."
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "📝 Next steps:"
echo "   1. Restart your dev server: npm run dev"
if [ "$SET_VERCEL" = "y" ] || [ "$SET_VERCEL" = "Y" ]; then
  if command -v vercel &> /dev/null; then
    echo "   2. Redeploy to Vercel: vercel --prod"
  else
    echo "   2. Redeploy to Vercel: npx vercel --prod"
  fi
fi
echo "   3. Run validation: npm run validate-env"
