#!/bin/bash
# Cloudflare Turnstile Environment Variables Setup Script
# Generated by scripts/generate-env-script.js
# Usage: ./scripts/setup-turnstile-env.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_DIR"

echo "🔐 Cloudflare Turnstile Environment Setup"
echo ""
echo "📋 Bot protection for forms"
echo ""




# Optional variables
echo ""
read -p "Do you want to set optional variables? (y/n): " SET_OPTIONAL



if [ "$SET_OPTIONAL" = "y" ] || [ "$SET_OPTIONAL" = "Y" ]; then
  echo ""
  echo "📝 VITE_TURNSTILE_SITE_KEY (Optional)"
  echo "   Turnstile site key (frontend)"
  echo "   Get from: https://dash.cloudflare.com/?to=/:account/turnstile"
  read -p "Enter VITE_TURNSTILE_SITE_KEY (or press Enter to skip): " VITE_TURNSTILE_SITE_KEY_INPUT
  VITE_TURNSTILE_SITE_KEY_VALUE="${VITE_TURNSTILE_SITE_KEY_INPUT}"
fi


# Build env file content
ENV_CONTENT="# Cloudflare Turnstile Configuration
# Generated by setup-turnstile-env.sh
"




if [ "$SET_OPTIONAL" = "y" ] || [ "$SET_OPTIONAL" = "Y" ] && [ -n "$VITE_TURNSTILE_SITE_KEY_VALUE" ]; then
  ENV_CONTENT+="VITE_TURNSTILE_SITE_KEY=$VITE_TURNSTILE_SITE_KEY_VALUE\n"
fi


# Append to .env.local (or create if doesn't exist)
if [ -f .env.local ]; then
  # Remove existing entries for these variables
  
  grep -v "^VITE_TURNSTILE_SITE_KEY=" .env.local > .env.local.tmp || true
  mv .env.local.tmp .env.local
  
fi

echo -e "$ENV_CONTENT" >> .env.local

echo ""
echo "✅ Cloudflare Turnstile environment variables added to .env.local!"

# Ask about Vercel
echo ""
read -p "Do you want to set Vercel environment variables? (y/n): " SET_VERCEL

if [ "$SET_VERCEL" = "y" ] || [ "$SET_VERCEL" = "Y" ]; then
  echo ""
  echo "🔐 Checking Vercel CLI..."
  
  # Use npx vercel if vercel command not found
  if command -v vercel &> /dev/null; then
    VERCEL_CMD="vercel"
  else
    VERCEL_CMD="npx vercel"
    echo "⚠️  Using npx vercel (Vercel CLI not installed globally)"
  fi
  
  echo "📝 Setting Vercel environment variables..."
  



  if [ -n "$VITE_TURNSTILE_SITE_KEY_VALUE" ]; then
    echo "$VITE_TURNSTILE_SITE_KEY_VALUE" | $VERCEL_CMD env add VITE_TURNSTILE_SITE_KEY production preview development 2>/dev/null || \
      echo "⚠️  VITE_TURNSTILE_SITE_KEY might already be set. Use '$VERCEL_CMD env ls' to check."
  fi


  echo ""
  echo "✅ Vercel environment variables set!"
  echo "   Run '$VERCEL_CMD --prod' to redeploy with new variables."
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "📝 Next steps:"
echo "   1. Restart your dev server: npm run dev"
if [ "$SET_VERCEL" = "y" ] || [ "$SET_VERCEL" = "Y" ]; then
  if command -v vercel &> /dev/null; then
    echo "   2. Redeploy to Vercel: vercel --prod"
  else
    echo "   2. Redeploy to Vercel: npx vercel --prod"
  fi
fi
echo "   3. Run validation: npm run validate-env"
